# PID values to use for JacoJointControlLocalImpl if Joint::SetVelocity()
# is to be used instead of Joint::SetForce().

jaco:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  

  # Position Controllers ---------------------------------------
  jaco_arm_0_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: jaco_arm_0_joint
    pid: {p: 20, i: 1.0, d: 0}
  jaco_arm_1_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: jaco_arm_1_joint
    pid: {p: 20, i: 1.0, d: 0}
  jaco_arm_2_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: jaco_arm_2_joint
    pid: {p: 20, i: 1.0, d: 0}
  jaco_arm_3_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: jaco_arm_3_joint
    pid: {p: 20, i: 1.0, d: 0}
  jaco_arm_4_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: jaco_arm_4_joint
    pid: {p: 20, i: 1.0, d: 0}
  jaco_arm_5_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: jaco_arm_5_joint
    pid: {p: 20, i: 1.0, d: 0}
  jaco_finger_joint_0_position_controller:
    type: position_controllers/JointPositionController
    joint: jaco_finger_joint_0
    pid: {p: 20, i: 1.0, d: 0}
  jaco_finger_joint_2_position_controller:
    type: position_controllers/JointPositionController
    joint: jaco_finger_joint_2
    pid: {p: 20, i: 1.0, d: 0}
  jaco_finger_joint_4_position_controller:
    type: position_controllers/JointPositionController
    joint: jaco_finger_joint_4
    pid: {p: 20, i: 1.0, d: 0}

  # Velocity Controllers ---------------------------------------
  # old values for all: p: 0.8 i: 0.4 d: 0
  jaco_arm_0_joint_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: jaco_arm_0_joint
    pid: {p: 0.4, i: 0, d: 0}  
  jaco_arm_1_joint_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: jaco_arm_1_joint
    pid: {p: 0.4, i: 0, d: 0}
  jaco_arm_2_joint_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: jaco_arm_2_joint
    pid: {p: 0.4, i: 0, d: 0}
  jaco_arm_3_joint_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: jaco_arm_3_joint
    pid: {p: 0.4, i: 0, d: 0}
  jaco_arm_4_joint_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: jaco_arm_4_joint
    pid: {p: 0.4, i: 0, d: 0}
  jaco_arm_5_joint_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: jaco_arm_5_joint
    pid: {p: 0.4, i: 0, d: 0}
  jaco_finger_joint_0_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: jaco_finger_joint_0
    pid: {p: 0.4, i: 0, d: 0}
  jaco_finger_joint_2_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: jaco_finger_joint_2
    pid: {p: 0.4, i: 0, d: 0}
  jaco_finger_joint_4_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: jaco_finger_joint_4
    pid: {p: 0.4, i: 0, d: 0}
